### ISSUE TITLE
[BUG] Diacritical Mark displayed error for Svan language

### ISSUE THREAD

**Issue by razmikb** [common-voice/common-voice#4879]
**Describe the bug**
1. On the default font (see screenshot 1) the diacritical signs are tilted to right. 
2. On the FiraGO font (see screenshot 2) the diacritical signs are tilted to right for the top menu where the [Mtarvruli](https://en.wikipedia.org/wiki/Georgian_Extended) script is used. Plus, two dots are clipped on the main text.  

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/sva 
2. Look at the upper menu and and first block of text
3. See error

**Expected behavior**
The diacritical signs should on top of the letters, symmetrically, not tilted to the right. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/773aed4a-5c19-4d07-902c-7ff7ddb7fe1f)

![Image](https://github.com/user-attachments/assets/04a37a46-063a-4928-8d58-c7f02076f80b)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 137.0.2 (64-bit) 

**Additional context**
As far as I know Svan language doesn't have Unicode support. That might the reason of this error.

**Comment by moz-kathyreid** [comment]
I tried to replicate this on Linux and was unable to: 

1. Firefox Developer 138.0b9 (64-bit) on Linux 
2. Chrome Version 133.0.6943.98 (Official Build) (64-bit) on Linux 
3. Firefox on Android 

All three do not exhibit the same rendering issue as described. 

1. Firefox Developer on Linux 

![Image](https://github.com/user-attachments/assets/a4768990-6371-4746-a75c-8997f4e12b6e)

2. Chrome on Linux 

![Image](https://github.com/user-attachments/assets/1c0686ee-ec7a-4ee8-9818-6158fe466847)

3. Firefox on Android 

![Image](https://github.com/user-attachments/assets/c5514dd1-aae6-491b-bf7d-a08348830131)

![Image](https://github.com/user-attachments/assets/aeb205a1-c243-40ef-a932-979f7d561b63)

I am currently running a dev environment in Docker on Linux and don't want to boot into another OS, but this is likely a combination of Windows rendering / fonts at this stage.

**Comment by HarikalarKutusu** [comment]
This is from Win 11, Opera latest (Chromium) - Do these have any problem @razmikb?

![Image](https://github.com/user-attachments/assets/7053ec6b-a9b4-4c3a-bc75-eb4a2c0aeb90)

**Comment by razmikb** [comment]
@HarikalarKutusu nope, they look as they should

**Comment by HarikalarKutusu** [comment]
@razmikb, can it be that you are forcing the browser to use a special font? What happens with the default font provided by MCV?

**Comment by razmikb** [comment]
@HarikalarKutusu The first screenshot is the default Firefox font.

**Comment by HarikalarKutusu** [comment]
Hey @razmikb, I became aware of the fact that the `fonts.gstatic.com` domain is blacklisted by many privacy enhanced browsers and  related extensions. Can you please check if this is the case for you? Any additional info on your settings will help much.

**Comment by moz-bozden** [comment]
Hi @razmikb , is this still an issue?
We will be handling this in our new code and like to close this if there are no such issues.

**Comment by razmikb** [comment]
Hi @moz-bozden , just checked, yes, issue is still the same way

**Comment by razmikb** [comment]
on the contribution page it looks good, the issue is on the front page.  <img width="1282" height="925" alt="Image" src="https://github.com/user-attachments/assets/ab03ba3d-985b-407c-a210-d66825627194" />

**Comment by razmikb** [comment]
And now that I look at it, not all symbols are rendered off center on the front page, here I put dots, greens for correct ones and reds for the wrong ones 

<img width="1373" height="742" alt="Image" src="https://github.com/user-attachments/assets/677c9fbd-9162-4a03-9da2-2d36fc8c7c3f" />

**Comment by moz-bozden** [comment]
Thank you @razmikb, we appreciate it.

It is clear now. It is because of the font used on those headers, it just cannot support the language.
It is the "Zilla Slab" font designed for Mozilla and only has full support for ~70 mostly Latin based scripts. It has limited support for others. It should fall back to Georgian, but I guess there is also an issue.
And, unfortunately the code does not support language based font-switching at that level.

We are currently working on combining the two apps, where I already implemented such facilities. This is why I tagged this issue "Monorepo". But I'll go ahead and check that exact sentence there...

**Comment by moz-bozden** [comment]
Still weird, because I cannot replicate it. I tested on:
- Win 11 Opera
- Win 11 Firefox Nightly
- Ubuntu Firefox
- Ubuntu Brave

Also tested on new system with new font, also OK.
It must be on your end @razmikb.
- Can you open the page with default settings (e.g. new default profile)?
- What about other browsers?

**Comment by razmikb** [comment]
Sure, here Private browsing on Firefox. titles still have issues. 

<img width="1913" height="1041" alt="Image" src="https://github.com/user-attachments/assets/2cee6b05-8999-4ee9-9a4d-8a46decb9968" />

and on Incognito Chrome it is even worse, all type of text is effected, not just titles.  

<img width="1888" height="1008" alt="Image" src="https://github.com/user-attachments/assets/572cf1ef-eb0e-40e5-8b18-b532dd2335db" />
