### ISSUE TITLE
[BUG] Can't create account from Spontaneous Speech, stuck in loop

### ISSUE THREAD

**Issue by ESBigeard** [common-voice/common-voice#4929]
**Describe the bug**
When you try to go on Spontaneous Speech without being logged-in, you're redirected to the page to create a Mozilla account. If you create an account from there, you get stuck in a loop and can never log-in or access anything else. This is fixed by manually going to the main Common Voice website, log-in from there, go to your profile, and accept privacy policy.

A normal user would not think of these steps to get stuck and would give up, so this is blocking for new users !

**To Reproduce**
1. Log out from Common Voice
2. Go to https://commonvoice.mozilla.org/spontaneous-speech/beta/prompts
3. You are redirected to the log-in process. Follow the process (I used directly e-mail to confirm the bug, but I had reports of it happening also when trying to sign-in from a Google account)
4. You'll notice you will be redirected again to the log-in screen and get stuck in a loop.

**Expected behavior**
Be redirected to Spontaneous Speech, be logged-in, and be able to start recording

**To fix**
1. Go to https://commonvoice.mozilla.org
2. Click log-in/sign-up
3. Select the e-mail/account you just tried to create. You'll be logged-in successfully this time. At this stage, if you try to connect to Spontaneous Speech, you'll again be directed to the screen to create an account.
4. Go to https://commonvoice.mozilla.org/en/profile/info
5. Scroll down to accept the privacy policy, click "save", accept the TOS in the pop-up that opens.
6. This time you can go to Spontaneous Speech successfully

**Desktop or Mobile (please complete the following information):**

- OS: Ubuntu 24.04.2 LTS
-   Browser : Firefox
-   Version : 139.0.1 (64-bit)

I had 2 different people confirm the bug in different hardware.

**Comment by moz-bozden** [comment]
Hey @ESBigeard, thank you for reporting. This is a known issue we have in our fix-it-list, a remnant from the merge of the SS beta.
As a workaround, go to main Scripted Speech and login from there, then go to the SS pages.
Sorry for the discomfort this causes...

**Comment by ESBigeard** [comment]
Okay, thank you for the quick answer. I understand that it's already in your fit-list, but I want to stress that it really is a big issue. We can't expect any new user to follow these steps, so that means Spontaneous Speech is currently limited to known Common Voice users.

**Comment by moz-bozden** [comment]
I fully agree. What you encounter is a redirection issue, which is rather easy to fix. It is based on having two different webapps with replicated menus and main pages.

To be on the same page: The user bases of these two webapps are not separate, SS uses user data from classic Common Voice.
So, when you are in SS and try to create a profile, you actually go to CV. There are several co-working issues there to be fixed before we can make them "seem like" a single application thou, some are harder to solve (like UI/dataset language handling differences, having different dataset languages/types).

**Comment by moz-bozden** [comment]
Hey @ESBigeard, I fixed the redirection issue and tested with different browsers clean and hardened ones. Also tested it on our test server. Is it possible that you check it on your end on the test server?
- Goto https://commonvoice.allizom.org/ (classic MCV, if you did not used it before you will be logged out, if not, you should log out)
- Open a new tab and go to https://commonvoice.allizom.org/spontaneous-speech/beta (SS main page, which needs registration). It should ask you to login/register (as it is a test server, it has no real data and gets reset, so you need to create a profile).
- It should redirect you back without any redirect loop.

Big thanks for reporting and your time 💯

**Comment by ESBigeard** [comment]
Still not fixed by following your instructions. I logged off and used a private tab to get a clean state, and tried in both Firefox and Chrome. If I click on "speak" then "answer question" I get directed to login/register and find the same loop. I'm available if you need screenshare or whatever else to test.

**Comment by moz-bozden** [comment]
Ahhh, it is not on the test server, I'll merge it and make test release shortly.

**Comment by moz-bozden** [comment]
@ESBigeard, sorry for the late answer, the fix is in the staging server I explained above.
Could you please give another shot to see if it is working on your end as expected?

**Comment by ESBigeard** [comment]
@moz-bozden No, still no change, sorry. I'm doing my tests on a fresh private tab. Tell me if I need to do a particular manipulation to empty a cache or something of that nature.

**Comment by HarikalarKutusu** [comment]
I cannot replicate it - it works on the test server here. Just tested like this:
- Opened two private tabs in Opera
- On SS page it asked me for login, selected login with Google, used my private gmail address.
- It showed me my email address on top-right, and when I refresh the other tab, CV app also shows my username and profile pic.

**Comment by ESBigeard** [comment]
I'm following exactly those instructions :

- Goto https://commonvoice.allizom.org/ 
- Open a new tab and go to https://commonvoice.allizom.org/spontaneous-speech/beta (SS main page, which needs registration). It should ask you to login/register

Tested in both Firefox and Chrome. Tried both direct e-mail with yopmail adresses, and login with Google with a freshly created google account.

**Comment by HarikalarKutusu** [comment]
Can you please open the console from developer tools and post any errors popping up there?
(tested again with Firefox - Nightly with no problems)

**Comment by ESBigeard** [comment]
Here's what I get when I click "sign in" and get looped back to it (category "info" hidden, tell me if you need it too)

```
Navigated to https://commonvoice.allizom.org/callback?code=2bcb4658a36e76207995ef7b02c3812f72b21f7a4c0440281b09db1eaaa75df1&state=U2FsdGVkX18RZmO2WBiFBJQcSEK5HKVYxeLZtDHJvl5dnqn4qhFPMF9Q19mpcB1G9nfesu%2Bzx4wnCpocuEq9UGkTFv%2FXROqjl17tzF2deJechL94Nt%2FLw5I7uo7CEdcIQdhq8VK8nNk4hbYGRyxD0nAKM%2FTONqeJ5GX8rD2iQSHJ%2FFyI7o9vdBPezxfvoksC%2BDGJRTCqf6KZFaxGdIT%2FWPyk3bwGNKicu3wGhMpBSys%3D

Uncaught TypeError: l is undefined
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:34
    n https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:13
    n https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:13
    n https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js:1
[react-modal.min.js:34:9444](https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js)

Navigated to https://commonvoice.allizom.org/login?redirect=https://commonvoice.allizom.org/spontaneous-speech/beta
```

**Comment by moz-bozden** [comment]
Hey @ESBigeard, I finally could reproduce this.
We each have several accounts we've been using for testing, but these are existing ones.
As we already know the redirection issue (even for existing accounts), I thought it was solved.
I did not read your initial post carefully which says "If you create an account from there...". Of course `create != login`.
When I created a new one from SS page, I saw what you mean.

We released the current changes to production, so people with existing accounts can login from anywhere, including SS pages with correct redirection.

And we started to work on your bug report.
Much grateful  💯

**Comment by ESBigeard** [comment]
Hello, I'm bumping up this bug. Just checked, the loop is still here if you *create* an account from clicking on the Spontaneous Speech button. I understand that you have a lot of work and I don't mean to be rude, just stating that it's still blocking the launch of our campaign for languages of France and it's going to cause issues for us soon.

**Comment by moz-bozden** [comment]
Hey @ESBigeard, it is at the top of our to-do list for this week.
It is not an easy one, but I think we can at least provide a workaround...

**Comment by ESBigeard** [comment]
Thank you! When you speak of workaround, please remember that we want the users to be able to use the website without specific instructions. Otherwise, the current situation would already work (just create an account first on the home page, *then* go to Spontaneous Speech).

**Comment by moz-bozden** [comment]
The problem we have is the Auth provider, which is out of our hands. It returns to a callback address (it is how it works), and our code redirects to where the user comes from - or make the user fill the Profile form first if it is a new user.
In Spontaneous Speech (SS) case, for new users, it skips the profile form stage and redirects back to the SS, where it loops.

It should work like this, and the fix should include it (documenting here to copy-paste):

1. It should not effect normal operation in CV
2. When existing user comes into SS as logged-out, the user should login and go back to SS page
3. When it is a new user, it should go to the profile page and stay there after save. It will NOT go back automatically to SS. **The user should re-select the menu item to go to SS functionality <= We just need to provide this and inform people, but it is a bit obvious from the UX perspective I think.***

Our problem lies from the fact that the Auth provider does not give information about new/old users...
In my definition the "workaround" is a non-ideal way of doing it, this time detecting a "new user"...

Would step no 3 work for you?

**Comment by ESBigeard** [comment]
That sounds perfectly fine and only a very slight annoyance. Works for us! Thank you again in advance for taking care of it.

**Comment by ESBigeard** [comment]
Hello, just reporting that the issue still exists.

**Comment by ESBigeard** [comment]
Hello! Our plan is to direct users to http://commonvoice.com/login in our social media posts, instead of the home page, to go around this bug. From an UX point of view, it seems to work! But I've noticed that doing so directs people to the English version of Common Voice, once they have created their account. Even when their browser settings would have auto selected their preferred language if they were starting from http://commonvoice.com . They can always change the language of the interface of course, but I'm currently running UX tests and people don't find that functionality, especially on mobile where it's hidden away in a menu. It's a much smaller issue to have, but still, does anyone have an idea on how to go around that second problem? A way to direct people directly and easily to the page to create their account, then redirect them to Common Voice in their browser's preferred language.

Also, should I open another issue to report this behaviour?

**Comment by moz-bozden** [comment]
@ESBigeard, I'm afraid that would not work... There are a couple of things in play here - some of which are preventing me to provide a solution, even a workaround... Sorry, a bit technical...

1. The `/login` route directly gets you to the backend where there is no info on the browser
2. There are multiple Auth providers and we don't have any control of them. But if we can send a "locale" information to them (from the backend - if it gets that info from the front-end), they reflect that back to us (and they show the login form in that language if supported). This is what we should make use of.
3. There are a couple of points where a user's language can be set - without effecting other users:
  - A first time user can mostly get that from the first browser language (there are other players there, such as privacy focused browsers and/or extensions which try to suppress much info, sometimes randomly, to prevent fingerprinting). But according to my tests the first one is used. So when you give the main site link the browser preferred language will be honored. But we don't save this info, because many people might use another main language and would like to provide support for another language. **That info is in the URL though - for CV**...
  - When a user selects a language from the pulldown menu - regardless of their login/logout status - that information gets recorded in local-storage of the browser. If an old user logs in and there is no such info in local storage (e.g, cleaned or another device/browser) the first language in their selected languages will be selected and saved into local-storage. This mechanism also provides language connection between two webapps (CV & SS), but unfortunately it will most probably not work in WebViews (see below).
  - As of now, the backend gets the locale info from the URL - but this is only valid for CV, because SS does not have it in the URL - so only local-storage value can be used here. **As of now I'm trying to implement this: passing that value to `/login` endpoint from the Login/Sign UP button...**
4. Login page is called from many places - where an anonymous user has no access, which includes the whole SS. Normal operation is -after logging in successfully- to redirect the user to that page. This is accomplished by the "referrer" (keeping where it came from) and they will be redirected there. As most users will re-login and only some will be new users, we cannot change this behavior (this is where I failed, still trying to figure out a way).
5. **WebViews**: These are secure and stripped-down browsers used by mobile apps. These are used by social media apps, so that a webpage is opened in that app, and when the user hits the back button, you will be in the same app. There is no way to open a link in a browser app, which is another app, this is prevented at operating system level, due to security reasons. **But: A user cannot record in a WebView, it is prevented**. There are a plethora of WebView implementations, but I did not see any allowing it. Even Instagram does not have clickable links.

I did a couple of social media campaigns and already hit these road-blocks, so I can suggest the following (assuming `fr` here):

1. Give them the main CV address: `https://commonvoice.mozilla.org/fr`
2. For mobile users: Ask them to copy paste the address to their browser application
3. Ask them click the `Login` button at the top-right and fill the profile, select the language (e.g. first French, then Picard) and variants, accents etc. and hit `SAVE` button.
4. Now they can select CS and/or SS related menu items and contribute.

This is the designed workflow and it will work. But I'm working on two things (to repeat):
- Make use of local-storage value to pass to `/login` at the backend
- Still try to solve the endless redirect problem.

**Comment by ESBigeard** [comment]
Thank you for the detailed explanations, it's very clear. I understood that something was transmitted when actually clicking on the "login" buttom from the homepage, that would be impossible to keep when coming directly to the /login url. So I'm not surprised by your answer. It's still a better solution for us than having users stuck in the login loop.

I'll try your solution with new users and see what works best. Thank you!

**Comment by moz-bozden** [comment]
@ESBigeard, here is one document I created before the campaign for Circassian languages (I can share the Word file):
https://bit.ly/cv_circassian_docs_user_manual_en

This, plus building a Telegram group and sharing some annotated screen-captured videos helped a lot. We also had a YouTube channel, did a lot of online group education... All channels are provided here: https://github.com/common-voice/common-voice/blob/main/docs/COMMUNITIES.md

**Comment by ESBigeard** [comment]
Nice user manual, very detailed. We're trying to keep the barrier of entry low, so this is not the kind of approach we're going to use, but it does give ideas thank you.

The communities list is useful. Between Matrix, Discourse, Discord and everything else, it's hard to keep track of everything. I'm saving this one, thanks.

Edit : The Discord link in this list is expired, for your information.

**Comment by HarikalarKutusu** [comment]
@ESBigeard, this should be fixed in https://github.com/common-voice/common-voice/issues/4929
I sent a PM to you and waiting your test results...

**Comment by moz-bozden** [comment]
We tested, the looping issue is gone, but the redirection is not fully working as intended (returns to the home page of SS).
If you consider this as resolved, we can close this,
I'll look at the redirection to correct page independent of this (the fix is already merged).

**Comment by ESBigeard** [comment]
Solved for me! Thank you again
